/**
 * generated by Xtext 2.9.1
 */
package edu.uniandes.automatizacion.sql_crud_generator.ui.contentassist;

import edu.uniandes.automatizacion.sql_crud_generator.ui.contentassist.AbstractSqlCrudGeneratorProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SqlCrudGeneratorProposalProvider extends AbstractSqlCrudGeneratorProposalProvider {
}
