/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.serializer;

import org.xtext.example.mydsl.serializer.AbstractMyDslSyntacticSequencer;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractMyDslSyntacticSequencer {
}
