/*
 * generated by Xtext 2.9.1
 */
package uniandes.automat.sql.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import uniandes.automat.sql.ui.internal.SqlActivator;

public class SqlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SqlActivator.getInstance().getInjector("uniandes.automat.sql.Sql");
	}

}
