/*
 * generated by Xtext 2.9.1
 */
package edu.uniandes.automatizacion.sql_crud_generator.tests

import com.google.inject.Inject
import edu.uniandes.automatizacion.sql_crud_generator.sqlCrudGenerator.Schema
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(SqlCrudGeneratorInjectorProvider)
class SqlCrudGeneratorParsingTest{

	@Inject
	ParseHelper<Schema> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
