/*
 * generated by Xtext
 */
package com.uniandes.jsontosql.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JsonRuntimeModule extends com.uniandes.jsontosql.xtext.AbstractJsonRuntimeModule {

}
