/**
 * generated by Xtext 2.9.1
 */
package org.uniandes.edu.co.validation;

import org.uniandes.edu.co.validation.AbstractSqlCrudValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SqlCrudValidator extends AbstractSqlCrudValidator {
}
