/**
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.tallerM2M;

import co.edu.uniandes.tallerM2M.AbstractSqlRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SqlRuntimeModule extends AbstractSqlRuntimeModule {
}
