/**
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.tallerM2M.sql;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Foreign Key</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link co.edu.uniandes.tallerM2M.sql.ForeignKey#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.uniandes.tallerM2M.sql.ForeignKey#getReferenceTable <em>Reference Table</em>}</li>
 *   <li>{@link co.edu.uniandes.tallerM2M.sql.ForeignKey#getReferenceColumn <em>Reference Column</em>}</li>
 * </ul>
 * </p>
 *
 * @see co.edu.uniandes.tallerM2M.sql.SqlPackage#getForeignKey()
 * @model
 * @generated
 */
public interface ForeignKey extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see co.edu.uniandes.tallerM2M.sql.SqlPackage#getForeignKey_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link co.edu.uniandes.tallerM2M.sql.ForeignKey#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Reference Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reference Table</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference Table</em>' reference.
   * @see #setReferenceTable(Tabla)
   * @see co.edu.uniandes.tallerM2M.sql.SqlPackage#getForeignKey_ReferenceTable()
   * @model
   * @generated
   */
  Tabla getReferenceTable();

  /**
   * Sets the value of the '{@link co.edu.uniandes.tallerM2M.sql.ForeignKey#getReferenceTable <em>Reference Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference Table</em>' reference.
   * @see #getReferenceTable()
   * @generated
   */
  void setReferenceTable(Tabla value);

  /**
   * Returns the value of the '<em><b>Reference Column</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reference Column</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference Column</em>' reference.
   * @see #setReferenceColumn(Columna)
   * @see co.edu.uniandes.tallerM2M.sql.SqlPackage#getForeignKey_ReferenceColumn()
   * @model
   * @generated
   */
  Columna getReferenceColumn();

  /**
   * Sets the value of the '{@link co.edu.uniandes.tallerM2M.sql.ForeignKey#getReferenceColumn <em>Reference Column</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference Column</em>' reference.
   * @see #getReferenceColumn()
   * @generated
   */
  void setReferenceColumn(Columna value);

} // ForeignKey
