/**
 * generated by Xtext 2.9.1
 */
package edu.uniandes.automatizacion.sql_crud_generator;

import edu.uniandes.automatizacion.sql_crud_generator.AbstractSqlCrudGeneratorRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SqlCrudGeneratorRuntimeModule extends AbstractSqlCrudGeneratorRuntimeModule {
}
