/**
 *
 * $Id$
 */
package cobiw.validation;

import cobiw.Copy;
import cobiw.Join;
import cobiw.TipoPrograma;
import cobiw.Variable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link cobiw.Programa}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProgramaValidator {
	boolean validate();

	boolean validateContiene(EList<Copy> value);
	boolean validateTipo(TipoPrograma value);
	boolean validateNombre(String value);
	boolean validateUsa(EList<Variable> value);
	boolean validateJoins(EList<Join> value);
	boolean validateAutor(String value);
	boolean validateTeam(String value);
	boolean validateObjetivo(String value);
	boolean validateNumeroRequerimiento(String value);
	boolean validateProgramaId(String value);
}
