/**
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class GenSqlDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
