/**
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.validation;

import co.edu.uniandes.validation.AbstractGenSqlValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GenSqlValidator extends AbstractGenSqlValidator {
}
