/*
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.ui.tests;

import co.edu.uniandes.GrammarSql.ui.internal.GrammarSqlActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class GrammarSqlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GrammarSqlActivator.getInstance().getInjector("co.edu.uniandes.GrammarSql");
	}

}
