/*
* generated by Xtext
*/
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPaginaAccess().getAlternatives(), "rule__Pagina__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEstiloAccess().getAlternatives(), "rule__Estilo__Alternatives");
					put(grammarAccess.getTipoPresentacionAccess().getAlternatives(), "rule__TipoPresentacion__Alternatives");
					put(grammarAccess.getMarketPlaceAccess().getGroup(), "rule__MarketPlace__Group__0");
					put(grammarAccess.getPromocionAccess().getGroup(), "rule__Promocion__Group__0");
					put(grammarAccess.getMapaAccess().getGroup(), "rule__Mapa__Group__0");
					put(grammarAccess.getContactoAccess().getGroup(), "rule__Contacto__Group__0");
					put(grammarAccess.getCatalogoAccess().getGroup(), "rule__Catalogo__Group__0");
					put(grammarAccess.getMarketPlaceAccess().getNombreAssignment_31(), "rule__MarketPlace__NombreAssignment_31");
					put(grammarAccess.getMarketPlaceAccess().getPresentacionAssignment_34(), "rule__MarketPlace__PresentacionAssignment_34");
					put(grammarAccess.getMarketPlaceAccess().getPaginasAssignment_36(), "rule__MarketPlace__PaginasAssignment_36");
					put(grammarAccess.getPromocionAccess().getNombreAssignment_5(), "rule__Promocion__NombreAssignment_5");
					put(grammarAccess.getPromocionAccess().getEstiloAssignment_8(), "rule__Promocion__EstiloAssignment_8");
					put(grammarAccess.getMapaAccess().getNombreAssignment_5(), "rule__Mapa__NombreAssignment_5");
					put(grammarAccess.getMapaAccess().getEstiloAssignment_8(), "rule__Mapa__EstiloAssignment_8");
					put(grammarAccess.getContactoAccess().getNombreAssignment_5(), "rule__Contacto__NombreAssignment_5");
					put(grammarAccess.getContactoAccess().getEstiloAssignment_8(), "rule__Contacto__EstiloAssignment_8");
					put(grammarAccess.getCatalogoAccess().getNombreAssignment_5(), "rule__Catalogo__NombreAssignment_5");
					put(grammarAccess.getCatalogoAccess().getEstiloAssignment_8(), "rule__Catalogo__EstiloAssignment_8");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser) parser;
			typedParser.entryRuleMarketPlace();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
