/**
 * generated by Xtext 2.9.1
 */
package org.uniandes.xtext.ui.contentassist;

import org.uniandes.xtext.ui.contentassist.AbstractSQLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SQLProposalProvider extends AbstractSQLProposalProvider {
}
