/**
 *
 * $Id$
 */
package proyectos.validation;

import org.eclipse.emf.common.util.EList;

import proyectos.Pagina;
import proyectos.TipoPresentacion;

/**
 * A sample validator interface for {@link proyectos.MarketPlace}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MarketPlaceValidator {
	boolean validate();

	boolean validatePaginas(EList<Pagina> value);

	boolean validateNombre(String value);

	boolean validatePresentacion(TipoPresentacion value);
}
