/**
 * generated by Xtext 2.9.1
 */
package uniandes.automat.sql.sql;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Key</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uniandes.automat.sql.sql.PrimaryKey#getCol <em>Col</em>}</li>
 * </ul>
 *
 * @see uniandes.automat.sql.sql.SqlPackage#getPrimaryKey()
 * @model
 * @generated
 */
public interface PrimaryKey extends EObject
{
  /**
   * Returns the value of the '<em><b>Col</b></em>' reference list.
   * The list contents are of type {@link uniandes.automat.sql.sql.Column}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Col</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col</em>' reference list.
   * @see uniandes.automat.sql.sql.SqlPackage#getPrimaryKey_Col()
   * @model
   * @generated
   */
  EList<Column> getCol();

} // PrimaryKey
