/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.sQL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.sQL.Table#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.sQL.Table#getColumns <em>Columns</em>}</li>
 *   <li>{@link org.xtext.example.sQL.Table#getPrimaryKey <em>Primary Key</em>}</li>
 *   <li>{@link org.xtext.example.sQL.Table#getForeignkeys <em>Foreignkeys</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.sQL.SQLPackage#getTable()
 * @model
 * @generated
 */
public interface Table extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.sQL.SQLPackage#getTable_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.sQL.Table#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Columns</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.sQL.column}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Columns</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Columns</em>' containment reference list.
   * @see org.xtext.example.sQL.SQLPackage#getTable_Columns()
   * @model containment="true"
   * @generated
   */
  EList<column> getColumns();

  /**
   * Returns the value of the '<em><b>Primary Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Primary Key</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primary Key</em>' containment reference.
   * @see #setPrimaryKey(primaryKey)
   * @see org.xtext.example.sQL.SQLPackage#getTable_PrimaryKey()
   * @model containment="true"
   * @generated
   */
  primaryKey getPrimaryKey();

  /**
   * Sets the value of the '{@link org.xtext.example.sQL.Table#getPrimaryKey <em>Primary Key</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primary Key</em>' containment reference.
   * @see #getPrimaryKey()
   * @generated
   */
  void setPrimaryKey(primaryKey value);

  /**
   * Returns the value of the '<em><b>Foreignkeys</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.sQL.foreignKey}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Foreignkeys</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Foreignkeys</em>' containment reference list.
   * @see org.xtext.example.sQL.SQLPackage#getTable_Foreignkeys()
   * @model containment="true"
   * @generated
   */
  EList<foreignKey> getForeignkeys();

} // Table
