/*
 * generated by Xtext 2.9.1
 */
package org.uniandes.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.uniandes.xtext.ide.contentassist.antlr.internal.InternalSQLParser;
import org.uniandes.xtext.services.SQLGrammarAccess;

public class SQLParser extends AbstractContentAssistParser {

	@Inject
	private SQLGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalSQLParser createParser() {
		InternalSQLParser result = new InternalSQLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
					put(grammarAccess.getDataBaseAccess().getGroup(), "rule__DataBase__Group__0");
					put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
					put(grammarAccess.getColumnAccess().getGroup(), "rule__Column__Group__0");
					put(grammarAccess.getColumnAccess().getGroup_1(), "rule__Column__Group_1__0");
					put(grammarAccess.getColumnAccess().getGroup_1_1(), "rule__Column__Group_1_1__0");
					put(grammarAccess.getPrimaryKeyAccess().getGroup(), "rule__PrimaryKey__Group__0");
					put(grammarAccess.getPrimaryKeyAccess().getGroup_4(), "rule__PrimaryKey__Group_4__0");
					put(grammarAccess.getForeignKeyAccess().getGroup(), "rule__ForeignKey__Group__0");
					put(grammarAccess.getForeignKeyAccess().getGroup_4(), "rule__ForeignKey__Group_4__0");
					put(grammarAccess.getForeignKeyAccess().getGroup_10(), "rule__ForeignKey__Group_10__0");
					put(grammarAccess.getDataBaseAccess().getTableAssignment_1(), "rule__DataBase__TableAssignment_1");
					put(grammarAccess.getTableAccess().getNameAssignment_2(), "rule__Table__NameAssignment_2");
					put(grammarAccess.getTableAccess().getColumnAssignment_4(), "rule__Table__ColumnAssignment_4");
					put(grammarAccess.getTableAccess().getPrimarykeyAssignment_5(), "rule__Table__PrimarykeyAssignment_5");
					put(grammarAccess.getTableAccess().getForeignkeyAssignment_6(), "rule__Table__ForeignkeyAssignment_6");
					put(grammarAccess.getColumnAccess().getNameAssignment_0(), "rule__Column__NameAssignment_0");
					put(grammarAccess.getColumnAccess().getTypeAssignment_1_0(), "rule__Column__TypeAssignment_1_0");
					put(grammarAccess.getColumnAccess().getIsNullAssignment_1_2(), "rule__Column__IsNullAssignment_1_2");
					put(grammarAccess.getPrimaryKeyAccess().getColumnAssignment_3(), "rule__PrimaryKey__ColumnAssignment_3");
					put(grammarAccess.getPrimaryKeyAccess().getColumnAssignment_4_1(), "rule__PrimaryKey__ColumnAssignment_4_1");
					put(grammarAccess.getForeignKeyAccess().getColumnAssignment_3(), "rule__ForeignKey__ColumnAssignment_3");
					put(grammarAccess.getForeignKeyAccess().getColumnAssignment_4_1(), "rule__ForeignKey__ColumnAssignment_4_1");
					put(grammarAccess.getForeignKeyAccess().getTableRefAssignment_7(), "rule__ForeignKey__TableRefAssignment_7");
					put(grammarAccess.getForeignKeyAccess().getColumnsRefAssignment_9(), "rule__ForeignKey__ColumnsRefAssignment_9");
					put(grammarAccess.getForeignKeyAccess().getColumnsRefAssignment_10_1(), "rule__ForeignKey__ColumnsRefAssignment_10_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalSQLParser typedParser = (InternalSQLParser) parser;
			typedParser.entryRuleDataBase();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SQLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SQLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
