/**
 * generated by Xtext 2.9.2
 */
package edu.uniandes.automatizacion.sql_crud_generator.sqlCrudGenerator;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.uniandes.automatizacion.sql_crud_generator.sqlCrudGenerator.DataType#getDataType <em>Data Type</em>}</li>
 *   <li>{@link edu.uniandes.automatizacion.sql_crud_generator.sqlCrudGenerator.DataType#getPrecision <em>Precision</em>}</li>
 * </ul>
 *
 * @see edu.uniandes.automatizacion.sql_crud_generator.sqlCrudGenerator.SqlCrudGeneratorPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends EObject
{
  /**
   * Returns the value of the '<em><b>Data Type</b></em>' attribute.
   * The literals are from the enumeration {@link edu.uniandes.automatizacion.sql_crud_generator.sqlCrudGenerator.ENUM_DATA_TYPE}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Type</em>' attribute.
   * @see edu.uniandes.automatizacion.sql_crud_generator.sqlCrudGenerator.ENUM_DATA_TYPE
   * @see #setDataType(ENUM_DATA_TYPE)
   * @see edu.uniandes.automatizacion.sql_crud_generator.sqlCrudGenerator.SqlCrudGeneratorPackage#getDataType_DataType()
   * @model
   * @generated
   */
  ENUM_DATA_TYPE getDataType();

  /**
   * Sets the value of the '{@link edu.uniandes.automatizacion.sql_crud_generator.sqlCrudGenerator.DataType#getDataType <em>Data Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Type</em>' attribute.
   * @see edu.uniandes.automatizacion.sql_crud_generator.sqlCrudGenerator.ENUM_DATA_TYPE
   * @see #getDataType()
   * @generated
   */
  void setDataType(ENUM_DATA_TYPE value);

  /**
   * Returns the value of the '<em><b>Precision</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Precision</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Precision</em>' attribute.
   * @see #setPrecision(int)
   * @see edu.uniandes.automatizacion.sql_crud_generator.sqlCrudGenerator.SqlCrudGeneratorPackage#getDataType_Precision()
   * @model
   * @generated
   */
  int getPrecision();

  /**
   * Sets the value of the '{@link edu.uniandes.automatizacion.sql_crud_generator.sqlCrudGenerator.DataType#getPrecision <em>Precision</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Precision</em>' attribute.
   * @see #getPrecision()
   * @generated
   */
  void setPrecision(int value);

} // DataType
