/**
 * generated by Xtext 2.9.1
 */
package org.uniandes.edu.co;

import org.uniandes.edu.co.SqlCrudStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SqlCrudStandaloneSetup extends SqlCrudStandaloneSetupGenerated {
  public static void doSetup() {
    SqlCrudStandaloneSetup _sqlCrudStandaloneSetup = new SqlCrudStandaloneSetup();
    _sqlCrudStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
