package co.edu.uniandes.proyectoautomatizacion.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table imagenSliderItemDb.
 */
public class ImagenSliderItemDb implements java.io.Serializable {

    private Long id;
    private String imagen;
    private String url;
    private String tipo;
    private String pantalla;

    public ImagenSliderItemDb() {
    }

    public ImagenSliderItemDb(Long id) {
        this.id = id;
    }

    public ImagenSliderItemDb(Long id, String imagen, String url, String tipo, String pantalla) {
        this.id = id;
        this.imagen = imagen;
        this.url = url;
        this.tipo = tipo;
        this.pantalla = pantalla;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImagen() {
        return imagen;
    }

    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getPantalla() {
        return pantalla;
    }

    public void setPantalla(String pantalla) {
        this.pantalla = pantalla;
    }

}
