/**
 *
 * $Id$
 */
package metamodeloNewsletter.validation;

import metamodeloNewsletter.Cell;

import metamodeloNewsletter.enums.Color;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link metamodeloNewsletter.Row}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RowValidator {
	boolean validate();

	boolean validateCells(EList<Cell> value);
	boolean validateHeight(int value);

	boolean validateHeight(String value);
	boolean validateBackgroundColor(Color value);
}
