<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="csharp" nsURI="http://www.example.org/csharp" nsPrefix="csharp">
  <eClassifiers xsi:type="ecore:EClass" name="Vista" instanceClassName="Vista">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementos" upperBound="-1"
        eType="#//Widget" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="esEntrada" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelo" lowerBound="1"
        eType="#//Modelo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controlador">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vistas" lowerBound="1"
        upperBound="-1" eType="#//Vista" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelos" upperBound="-1"
        eType="#//Modelo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modelo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propiedades" lowerBound="1"
        upperBound="-1" eType="#//Propiedad" containment="true" eOpposite="#//Propiedad/modelo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="esEntrada" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propiedad" eType="#//Propiedad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoWidget" eType="#//TipoWidget"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Propiedad">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitud" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelo" lowerBound="1"
        eType="#//Modelo" eOpposite="#//Modelo/propiedades"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="esRelleno" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Programa">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlador" lowerBound="1"
        eType="#//Controlador" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoPrograma" eType="#//TipoPrograma"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoPrograma">
    <eLiterals name="reporte"/>
    <eLiterals name="consulta" value="1"/>
    <eLiterals name="cobol" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoWidget">
    <eLiterals name="Input"/>
    <eLiterals name="Label"/>
    <eLiterals name="Boton"/>
    <eLiterals name="Tabla"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoDato">
    <eLiterals name="int"/>
    <eLiterals name="string"/>
    <eLiterals name="decimal"/>
  </eClassifiers>
</ecore:EPackage>
