/*
* generated by Xtext
*/
package org.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CsharpStandaloneSetup extends CsharpStandaloneSetupGenerated{

	public static void doSetup() {
		new CsharpStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

