/*
 * generated by Xtext 2.9.2
 */
package edu.uniandes.automatizacion.sql_crud_generator.ui;

import com.google.inject.Injector;
import edu.uniandes.automatizacion.sql_crud_generator.ui.internal.Sql_crud_generatorActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SqlCrudGeneratorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Sql_crud_generatorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Sql_crud_generatorActivator.getInstance().getInjector(Sql_crud_generatorActivator.EDU_UNIANDES_AUTOMATIZACION_SQL_CRUD_GENERATOR_SQLCRUDGENERATOR);
	}
	
}
