/*
 * generated by Xtext
 */
package com.uniandes.config2sql.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConfigUiModule extends com.uniandes.config2sql.xtext.ui.AbstractConfigUiModule {
	public ConfigUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
