/**
 * generated by Xtext 2.9.1
 */
package org.uniandes.xtext.sQL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.uniandes.xtext.sQL.Column;
import org.uniandes.xtext.sQL.ForeignKey;
import org.uniandes.xtext.sQL.SQLPackage;
import org.uniandes.xtext.sQL.Table;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Foreign Key</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.uniandes.xtext.sQL.impl.ForeignKeyImpl#getColumn <em>Column</em>}</li>
 *   <li>{@link org.uniandes.xtext.sQL.impl.ForeignKeyImpl#getTableRef <em>Table Ref</em>}</li>
 *   <li>{@link org.uniandes.xtext.sQL.impl.ForeignKeyImpl#getColumnsRef <em>Columns Ref</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ForeignKeyImpl extends MinimalEObjectImpl.Container implements ForeignKey
{
  /**
   * The cached value of the '{@link #getColumn() <em>Column</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumn()
   * @generated
   * @ordered
   */
  protected EList<Column> column;

  /**
   * The cached value of the '{@link #getTableRef() <em>Table Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTableRef()
   * @generated
   * @ordered
   */
  protected Table tableRef;

  /**
   * The cached value of the '{@link #getColumnsRef() <em>Columns Ref</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumnsRef()
   * @generated
   * @ordered
   */
  protected EList<Column> columnsRef;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ForeignKeyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SQLPackage.Literals.FOREIGN_KEY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Column> getColumn()
  {
    if (column == null)
    {
      column = new EObjectResolvingEList<Column>(Column.class, this, SQLPackage.FOREIGN_KEY__COLUMN);
    }
    return column;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Table getTableRef()
  {
    if (tableRef != null && tableRef.eIsProxy())
    {
      InternalEObject oldTableRef = (InternalEObject)tableRef;
      tableRef = (Table)eResolveProxy(oldTableRef);
      if (tableRef != oldTableRef)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SQLPackage.FOREIGN_KEY__TABLE_REF, oldTableRef, tableRef));
      }
    }
    return tableRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Table basicGetTableRef()
  {
    return tableRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTableRef(Table newTableRef)
  {
    Table oldTableRef = tableRef;
    tableRef = newTableRef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SQLPackage.FOREIGN_KEY__TABLE_REF, oldTableRef, tableRef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Column> getColumnsRef()
  {
    if (columnsRef == null)
    {
      columnsRef = new EObjectResolvingEList<Column>(Column.class, this, SQLPackage.FOREIGN_KEY__COLUMNS_REF);
    }
    return columnsRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SQLPackage.FOREIGN_KEY__COLUMN:
        return getColumn();
      case SQLPackage.FOREIGN_KEY__TABLE_REF:
        if (resolve) return getTableRef();
        return basicGetTableRef();
      case SQLPackage.FOREIGN_KEY__COLUMNS_REF:
        return getColumnsRef();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SQLPackage.FOREIGN_KEY__COLUMN:
        getColumn().clear();
        getColumn().addAll((Collection<? extends Column>)newValue);
        return;
      case SQLPackage.FOREIGN_KEY__TABLE_REF:
        setTableRef((Table)newValue);
        return;
      case SQLPackage.FOREIGN_KEY__COLUMNS_REF:
        getColumnsRef().clear();
        getColumnsRef().addAll((Collection<? extends Column>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SQLPackage.FOREIGN_KEY__COLUMN:
        getColumn().clear();
        return;
      case SQLPackage.FOREIGN_KEY__TABLE_REF:
        setTableRef((Table)null);
        return;
      case SQLPackage.FOREIGN_KEY__COLUMNS_REF:
        getColumnsRef().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SQLPackage.FOREIGN_KEY__COLUMN:
        return column != null && !column.isEmpty();
      case SQLPackage.FOREIGN_KEY__TABLE_REF:
        return tableRef != null;
      case SQLPackage.FOREIGN_KEY__COLUMNS_REF:
        return columnsRef != null && !columnsRef.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ForeignKeyImpl
