/**
 *
 * $Id$
 */
package webApiInput.validation;

import org.eclipse.emf.common.util.EList;

import webApiInput.Constructor;
import webApiInput.Metodo;
import webApiInput.Propiedad;

/**
 * A sample validator interface for {@link webApiInput.Clase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClaseValidator {
	boolean validate();

	boolean validatePropiedades(EList<Propiedad> value);
	boolean validateMetodos(EList<Metodo> value);
	boolean validateEnums(EList<webApiInput.Enum> value);
	boolean validateNamespace(String value);
	boolean validateSuper(String value);
	boolean validateConstructores(EList<Constructor> value);
}
