/**
 * generated by Xtext 2.9.1
 */
package org.uniandes.edu.co.sqlCrud;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Database</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.uniandes.edu.co.sqlCrud.Database#getTables <em>Tables</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.uniandes.edu.co.sqlCrud.SqlCrudPackage#getDatabase()
 * @model
 * @generated
 */
public interface Database extends EObject
{
  /**
   * Returns the value of the '<em><b>Tables</b></em>' containment reference list.
   * The list contents are of type {@link org.uniandes.edu.co.sqlCrud.Table}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tables</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tables</em>' containment reference list.
   * @see org.uniandes.edu.co.sqlCrud.SqlCrudPackage#getDatabase_Tables()
   * @model containment="true"
   * @generated
   */
  EList<Table> getTables();

} // Database
