/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.ui.AbstractSQLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SQLUiModule extends AbstractSQLUiModule {
  public SQLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
