/*
 * generated by Xtext 2.9.2
 */
package edu.uniandes.automatizacion.sql_crud_generator.ui.tests;

import com.google.inject.Injector;
import edu.uniandes.automatizacion.sql_crud_generator.ui.internal.Sql_crud_generatorActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class SqlCrudGeneratorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Sql_crud_generatorActivator.getInstance().getInjector("edu.uniandes.automatizacion.sql_crud_generator.SqlCrudGenerator");
	}

}
