/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.sql.ui.internal.SqlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SQLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SqlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SqlActivator.getInstance().getInjector(SqlActivator.ORG_XTEXT_EXAMPLE_SQL);
	}
	
}
